services:

  mysql:
    image: mysql:8.0
    container_name: de-mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: de_database
      MYSQL_ROOT_HOST: '%'
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3307:3306"
    volumes:
      - de_mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-padmin123"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  airflow-init:
    image: apache/airflow:2.8.1
    user: "${AIRFLOW_UID:-50000}:0"
    depends_on:
      mysql:
        condition: service_healthy
    entrypoint: /bin/bash
    command:
      - -c
      - >
        pip install mysql-connector-python &&
        sleep 10 &&
        airflow db migrate &&
        airflow users create --username admin --password admin123
        --firstname Admin --lastname User --role Admin --email admin@example.com
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: mysql+mysqlconnector://root:admin123@mysql:3306/de_database
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./scripts:/opt/airflow/scripts
      - ./data:/opt/airflow/data

  webserver:
    image: apache/airflow:2.8.1
    user: "${AIRFLOW_UID:-50000}:0"
    restart: on-failure
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: mysql+mysqlconnector://root:admin123@mysql:3306/de_database
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__CORE__DAGBAG_IMPORT_TIMEOUT: "120"
      AIRFLOW__CORE__DAG_FILE_PROCESSOR_TIMEOUT: "120"
      AIRFLOW__WEBSERVER__WORKER_TIMEOUT: "300"
      _PIP_ADDITIONAL_REQUIREMENTS: "mysql-connector-python pandas openpyxl python-dateutil"
    command: airflow webserver --worker-timeout 300 --workers 2
    ports:
      - "8081:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./scripts:/opt/airflow/scripts
      - ./data:/opt/airflow/data

  scheduler:
    image: apache/airflow:2.8.1
    user: "${AIRFLOW_UID:-50000}:0"
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: mysql+mysqlconnector://root:admin123@mysql:3306/de_database
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      _PIP_ADDITIONAL_REQUIREMENTS: "mysql-connector-python pandas openpyxl python-dateutil"
    command: airflow scheduler
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./scripts:/opt/airflow/scripts
      - ./data:/opt/airflow/data

volumes:
  de_mysql_data: